global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'polymarket'
    static_configs:
      - targets: [ 'localhost:9101' ]
        labels:
          currency: 'btc'
      - targets: [ 'localhost:9102' ]
        labels:
          currency: 'eth'
      - targets: [ 'localhost:9103' ]
        labels:
          currency: 'sol'
      - targets: [ 'localhost:9104' ]
        labels:
          currency: 'xrp'

