global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'polymarket'
    static_configs:
      - targets: [ '127.0.0.1:9101' ]
        labels:
          currency: 'btc'
      - targets: [ '127.0.0.1:9102' ]
        labels:
          currency: 'eth'
      - targets: [ '127.0.0.1:9103' ]
        labels:
          currency: 'sol'
      - targets: [ '127.0.0.1:9104' ]
        labels:
          currency: 'xrp'

